spring:
  application:
    name: mcloud-orders
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: mcloud-orders
    description: Order service for m-CRM Kafka course
    team: mentee-power

app:
  kafka:
    health-enabled: true
    topics:
      high: orders.priority.high
      normal: orders.priority.normal
      low: orders.priority.low

resilience4j:
  retry:
    instances:
      order-processing:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - ru.mentee.power.orders.adapters.integration.ExternalServiceException